-- ============================================================
--  REQUEST JOB — Production Engineer & IT
--  Database schema  (MySQL / MariaDB — XAMPP)
--  Import:  phpMyAdmin > Import  OR
--           mysql -u root < database.sql
-- ============================================================

CREATE DATABASE IF NOT EXISTS request_job
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE request_job;

-- ---------- users ----------
CREATE TABLE IF NOT EXISTS users (
  id            INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name          VARCHAR(150) NOT NULL,
  username      VARCHAR(60)  NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  department    VARCHAR(100) DEFAULT NULL,
  role          ENUM('user','engineer','admin') NOT NULL DEFAULT 'user',
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------- requests (one job ticket) ----------
CREATE TABLE IF NOT EXISTS requests (
  id             INT UNSIGNED NOT NULL AUTO_INCREMENT,
  rec_no         VARCHAR(20)  NOT NULL,                -- RJE-20260041 (not unique: editable, duplicates warned not blocked)
  -- ----- page 1 : requester -----
  req_date       DATE         DEFAULT NULL,
  for_section    VARCHAR(60)  DEFAULT 'IT',            -- IT / Production Engineer
  subject        VARCHAR(255) DEFAULT NULL,
  req_name       VARCHAR(150) DEFAULT NULL,
  position       VARCHAR(100) DEFAULT NULL,
  section        VARCHAR(100) DEFAULT NULL,
  due_date       DATE         DEFAULT NULL,
  detail         TEXT         DEFAULT NULL,
  picture_path   VARCHAR(255) DEFAULT NULL,
  pdf_path       VARCHAR(255) DEFAULT NULL,       -- attached report PDF
  -- ----- page 2 : engineer / IT -----
  operation_detail TEXT       DEFAULT NULL,
  date_received  DATE         DEFAULT NULL,
  schedule_date  DATE         DEFAULT NULL,
  finish_date    DATE         DEFAULT NULL,
  schedule_flag  ENUM('on_schedule','no_schedule') DEFAULT NULL,
  schedule_cause VARCHAR(255) DEFAULT NULL,
  result_status  VARCHAR(255) DEFAULT NULL,
  -- ----- workflow -----
  status         ENUM('pending','receive','waiting','finish','cancel')
                 NOT NULL DEFAULT 'pending',
  created_by     INT UNSIGNED DEFAULT NULL,
  created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY rec_no (rec_no),
  KEY idx_status (status),
  KEY idx_created_by (created_by),
  CONSTRAINT fk_req_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------- equipment to order (rows on page 2) ----------
CREATE TABLE IF NOT EXISTS request_equipment (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  request_id INT UNSIGNED NOT NULL,
  seq        INT          NOT NULL,
  item       VARCHAR(255) DEFAULT NULL,
  qty        VARCHAR(50)  DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_req (request_id),
  CONSTRAINT fk_eq_req FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------- login attempts (rate limiting) ----------
CREATE TABLE IF NOT EXISTS login_attempts (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username   VARCHAR(60)  NOT NULL,
  ip         VARCHAR(45)  NOT NULL,
  success    TINYINT(1)   NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_lookup (username, ip, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------- yearly running counter for REC.No ----------
CREATE TABLE IF NOT EXISTS rec_counter (
  year     INT NOT NULL,
  last_seq INT NOT NULL DEFAULT 0,
  PRIMARY KEY (year)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------- notifications ----------
CREATE TABLE IF NOT EXISTS notifications (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id    INT UNSIGNED NOT NULL,
  request_id INT UNSIGNED DEFAULT NULL,
  message    VARCHAR(255) NOT NULL,
  is_read    TINYINT(1)   NOT NULL DEFAULT 0,
  created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_user_unread (user_id, is_read),
  CONSTRAINT fk_notif_user FOREIGN KEY (user_id)    REFERENCES users(id)    ON DELETE CASCADE,
  CONSTRAINT fk_notif_req  FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- A default admin (admin / admin123) is created by running:  /request-job/seed.php
-- (password hashes must be generated by PHP, not hard-coded in SQL)
